name: Detect New Commit

on: push

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Notify about new commit
      run: echo "curl https://selective-proud-club.glitch.me/"
