 name: Detect New Commit

on: push

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notify about new commit
      run: echo "New commit detected: ${{ github.event.head_commit.message }}"
